export const en = {
    common: {
        welcome: 'Welcome',
        hello: 'Hello',
        goodbye: 'Goodbye',
        save: 'Save',
        cancel: 'Cancel',
        confirm: 'Confirm',
        delete: 'Delete',
        edit: 'Edit',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        oops: 'Oops!',
        screenNotFound: "This screen doesn't exist.",
        goHome: 'Go to home screen!',
        select: 'Select...',
        search: 'Search...',
        noResults: 'No results found',
        all: 'All',
        close: 'Close',
        pass: 'PASS',
        fail: 'FAIL',
    },
    home: {
        title: 'Home',
        description: 'Edit app/index.tsx to get started.',
        browseTheDocs: 'Browse the Docs',
        starTheRepo: 'Star the Repo',
        about: 'About',
    },
    navigator: {
        start: 'Start',
    },
    history: {
        title: 'History',
        follow: 'Follow',
        unfollow: 'Unfollow',
        hide: 'Hide',
        report: 'Report',
        friend: 'Friend',
        all: 'All',
        privateUser: 'Private User',
        noItems: 'No activities found',
        unknownResort: 'Unknown Location',
        detail: 'Activity Detail',
        runsDetail: 'Runs Detail',
        noRuns: 'No runs recorded',
        noLocations: 'No location data',
        run: 'Run',
        duration: 'Duration',
        avgSpeed: 'Avg Speed',
        verticalDrop: 'Vertical Drop',
    },
    localHistory: {
        title: 'My Records',
        noItems: 'No local records',
        noItemsDescription: 'Start tracking to see your records here',
        notSynced: 'Not synced',
    },
    rank: {
        title: 'Ranking',
        all: 'All',
        selectRegion: 'Select Region',
        selectResort: 'Select Resort',
        searchResort: 'Search resort...',
        noResorts: 'No resorts found',
        close: 'Close',
        noRankings: 'No rankings found',
        speed: 'Speed',
        distance: 'Distance',
        count: 'Count',
        countUnit: 'runs',
    },
    alarm: {
        title: 'Notifications',
        unread: 'Unread',
        markAllAsRead: 'Mark all as read',
        noAlarms: 'No notifications',
    },
    user: {
        title: 'Profile',
        editProfile: 'Edit Profile',
        profileImage: 'Profile Image',
        name: 'Name',
        bio: 'Bio',
        isPublic: 'Visibility',
        public: 'Public',
        private: 'Private',
        save: 'Save',
        cancel: 'Cancel',
        tapToChange: 'Tap to change',
        totalSummary: 'Total Summary',
        activityType: 'Activity Type',
        ski: 'Ski',
        snowboard: 'Snowboard',
        both: 'Ski & Snowboard',
    },
    auth: {
        login: 'Login',
        logout: 'Logout',
        loginRequired: 'Login Required',
        loginDescription: 'Sign in to your account to track your activities',
        continueWithGoogle: 'Continue with Google',
        continueWithApple: 'Continue with Apple',
        loginFailed: 'Login failed',
        tryAgain: 'Please try again',
    },
    settings: {
        title: 'Settings',
        language: 'Language',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        systemTheme: 'System',
        units: 'Units',
        temperature: 'Temperature',
        measurement: 'Measurement',
        celsius: '°C',
        fahrenheit: '°F',
        metric: 'Metric',
        imperial: 'Imperial',
        notifications: 'Notifications',
        feed: 'Feed',
        workout: 'Workout',
        goal: 'Goal',
        on: 'ON',
        off: 'OFF',
        data: 'Data',
        resortData: 'Resort Data',
        refreshResortData: 'Refresh Resort Data',
        resortDataUpdated: 'Resort data updated',
        resortDataUpToDate: 'Data is up to date',
        resortDataError: 'Failed to update data',
        version: 'Version',
        hiddenUsers: 'Hidden Users',
        manageHiddenUsers: 'Manage Hidden Users',
        noHiddenUsers: 'No hidden users',
        unhide: 'Unhide',
    },
    uicard: {
        type: 'Type',
        totalDistance: 'Total Distance',
        vertical: 'Vertical Drop',
        timeOnSlope: 'Active Time',
        maxSpeed: 'Max Speed',
        runs: 'Runs',
    },
    tracking: {
        totalDistance: 'Distance',
        maxVertical: 'Vertical',
        totalRuns: 'Runs',
        maxSpeed: 'Max Speed',
        totalTime: 'Time',
        timeOnSlope: 'Slope Time',
        skiing: 'Riding',
        lifting: 'On Lift',
        resting: 'Resting',
        restingAlert: 'You have been resting for over 30 minutes. Would you like to end tracking?',
    },
    recovery: {
        title: 'Previous record found',
        start: 'Start',
        distance: 'Distance',
        runs: 'Runs',
        runUnit: '',
        locationRecords: 'Location records',
        countUnit: '',
        resume: 'Continue',
        startNew: 'Start new',
        delete: 'Delete',
    },
    test: {
        title: 'Test',
        gpsSimulation: 'GPS Simulation',
        skiingSimul: 'Skiing Sim',
        liftSimul: 'Lift Sim',
        restingSimul: 'Resting Sim',
        fullDaySimul: 'Full Day (5 runs)',
        stopSimulation: 'Stop Simulation',
        playbackSpeed: 'Playback Speed:',
        unitTests: 'Unit Tests',
        runningTests: 'Running tests...',
        simulationTest: 'Simulation Test',
        syncTest: 'Sync Test',
        simulationResults: 'Simulation Results',
        syncResults: 'Sync Results:',
        location: 'Loc:',
        altitude: 'Alt:',
        speed: 'Speed:',
        liveStats: 'Live Stats',
        expectedRuns: 'Expected runs: 5',
    },
}
