export const en = {
    common: {
        welcome: 'Welcome',
        hello: 'Hello',
        goodbye: 'Goodbye',
        save: 'Save',
        cancel: 'Cancel',
        confirm: 'Confirm',
        delete: 'Delete',
        edit: 'Edit',
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
    },
    home: {
        title: 'Home',
        description: 'Edit app/index.tsx to get started.',
        browseTheDocs: 'Browse the Docs',
        starTheRepo: 'Star the Repo',
        about: 'About',
    },
    navigator: {
        start: 'Start',
    },
    history: {
        title: 'History',
        follow: 'Follow',
        unfollow: 'Unfollow',
        hide: 'Hide',
        report: 'Report',
        friend: 'Friend',
        all: 'All',
        privateUser: 'Private User',
        noItems: 'No activities found',
    },
    rank: {
        title: 'Ranking',
        selectCountry: 'Select Country',
        selectResort: 'Select Resort',
        searchCountry: 'Enter Country Name',
        searchResort: 'Enter Resort Name',
        selectCountryFirst: 'Select a country first',
        noRankings: 'No rankings found',
        speed: 'Speed',
        distance: 'Distance',
        count: 'Count',
    },
    alarm: {
        title: 'Notifications',
        unread: 'Unread',
        markAllAsRead: 'Mark all as read',
        noAlarms: 'No notifications',
    },
    user: {
        title: 'Profile',
        editProfile: 'Edit Profile',
        profileImage: 'Profile Image',
        name: 'Name',
        bio: 'Bio',
        isPublic: 'Visibility',
        public: 'Public',
        private: 'Private',
        save: 'Save',
        cancel: 'Cancel',
        tapToChange: 'Tap to change',
        totalSummary: 'Total Summary',
        activityType: 'Activity Type',
        ski: 'Ski',
        snowboard: 'Snowboard',
        both: 'Ski & Snowboard',
    },
    auth: {
        login: 'Login',
        logout: 'Logout',
        loginRequired: 'Login Required',
        loginDescription: 'Sign in to your account to track your activities',
        continueWithGoogle: 'Continue with Google',
        continueWithApple: 'Continue with Apple',
        loginFailed: 'Login failed',
        tryAgain: 'Please try again',
    },
    settings: {
        title: 'Settings',
        language: 'Language',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        systemTheme: 'System',
        units: 'Units',
        temperature: 'Temperature',
        measurement: 'Measurement',
        celsius: '°C',
        fahrenheit: '°F',
        metric: 'Metric',
        imperial: 'Imperial',
        notifications: 'Notifications',
        feed: 'Feed',
        workout: 'Workout',
        goal: 'Goal',
        on: 'ON',
        off: 'OFF',
    },
    uicard: {
        type: 'Type',
        totalDistance: 'Total Distance',
        vertical: 'Vertical',
        maxSpeed: 'Max Speed',
        timeOnSlope: 'Time on Slope',
        runs: 'Runs',
    },
    tracking: {
        totalDistance: 'Distance',
        maxVertical: 'Vertical',
        totalRuns: 'Runs',
        maxSpeed: 'Max Speed',
        totalTime: 'Time',
    },
}
