export const jp = {
    common: {
        welcome: 'ようこそ',
        hello: 'こんにちは',
        goodbye: 'さようなら',
        save: '保存',
        cancel: 'キャンセル',
        confirm: '確認',
        delete: '削除',
        edit: '編集',
        loading: '読み込み中...',
        error: 'エラー',
        success: '成功',
        oops: 'おっと!',
        screenNotFound: 'この画面は存在しません。',
        goHome: 'ホーム画面へ移動',
        select: '選択...',
        search: '検索...',
        noResults: '結果が見つかりません',
        all: 'すべて',
        close: '閉じる',
        pass: '合格',
        fail: '失敗',
    },
    home: {
        title: 'ホーム',
        description: 'app/index.tsxを編集して始めましょう。',
        browseTheDocs: 'ドキュメントを見る',
        starTheRepo: 'リポジトリにスターをつける',
        about: '紹介',
    },
    navigator: {
        start: 'スタート',
    },
    history: {
        title: '履歴',
        follow: 'フォロー',
        unfollow: 'フォロー解除',
        hide: '非表示',
        report: '通報',
        friend: '友達',
        all: 'すべて',
        privateUser: '非公開ユーザー',
        noItems: 'アクティビティがありません',
        unknownResort: '不明な場所',
        detail: 'アクティビティ詳細',
        runsDetail: '滑走詳細',
        noRuns: '滑走記録がありません',
        noLocations: '位置データがありません',
        run: '滑走',
        duration: '所要時間',
        avgSpeed: '平均速度',
        verticalDrop: '標高差',
    },
    localHistory: {
        title: 'マイ記録',
        noItems: 'ローカルに保存された記録がありません',
        noItemsDescription: 'トラッキングを開始すると記録が表示されます',
        notSynced: '未同期',
    },
    rank: {
        title: 'ランキング',
        all: 'すべて',
        selectRegion: '地域を選択',
        selectResort: 'スキー場を選択',
        searchResort: 'スキー場を検索...',
        noResorts: 'スキー場が見つかりません',
        close: '閉じる',
        noRankings: 'ランキングがありません',
        speed: '速度',
        distance: '滑走距離',
        count: '滑走回数',
        countUnit: '回',
    },
    alarm: {
        title: '通知',
        unread: '未読',
        markAllAsRead: 'すべて既読にする',
        noAlarms: '通知がありません',
    },
    user: {
        title: 'プロフィール',
        editProfile: 'プロフィール編集',
        profileImage: 'プロフィール画像',
        name: '名前',
        bio: '自己紹介',
        isPublic: '公開設定',
        public: '公開',
        private: '非公開',
        save: '保存',
        cancel: 'キャンセル',
        tapToChange: 'タップして変更',
        totalSummary: '合計',
        activityType: 'アクティビティタイプ',
        ski: 'スキー',
        snowboard: 'スノーボード',
        both: 'スキー & スノーボード',
    },
    auth: {
        login: 'ログイン',
        logout: 'ログアウト',
        loginRequired: 'ログインが必要です',
        loginDescription: 'アカウントにログインしてアクティビティを記録しましょう',
        continueWithGoogle: 'Googleで続ける',
        continueWithApple: 'Appleで続ける',
        loginFailed: 'ログインに失敗しました',
        tryAgain: 'もう一度お試しください',
    },
    settings: {
        title: '設定',
        language: '言語',
        theme: 'テーマ',
        darkMode: 'ダークモード',
        lightMode: 'ライトモード',
        systemTheme: 'システム',
        units: '単位',
        temperature: '温度',
        measurement: '測定',
        celsius: '°C',
        fahrenheit: '°F',
        metric: 'メートル法',
        imperial: 'ヤードポンド法',
        notifications: '通知',
        feed: 'フィード',
        workout: 'ワークアウト',
        goal: '目標',
        on: 'オン',
        off: 'オフ',
        data: 'データ',
        resortData: 'スキー場データ',
        refreshResortData: 'スキー場データを更新',
        resortDataUpdated: 'スキー場データが更新されました',
        resortDataUpToDate: '最新のデータです',
        resortDataError: 'データの更新に失敗しました',
        version: 'バージョン',
        hiddenUsers: '非表示ユーザー',
        manageHiddenUsers: '非表示ユーザーの管理',
        noHiddenUsers: '非表示ユーザーはいません',
        unhide: '表示する',
    },
    uicard: {
        type: 'タイプ',
        totalDistance: '総滑走距離',
        vertical: '標高差',
        maxSpeed: '最高速度',
        timeOnSlope: '滑走時間',
        runs: '滑走本数',
    },
    tracking: {
        totalDistance: '距離',
        maxVertical: '標高差',
        totalRuns: '本数',
        maxSpeed: '最高速度',
        totalTime: '経過時間',
        timeOnSlope: '滑走時間',
        skiing: '滑走中',
        lifting: 'リフト乗車中',
        resting: '休憩中',
        restingAlert: '30分以上移動していません。記録を終了しますか？',
    },
    recovery: {
        title: '以前の記録があります',
        start: '開始',
        distance: '距離',
        runs: '本数',
        runUnit: '本',
        locationRecords: '位置記録',
        countUnit: '件',
        resume: '続けて記録',
        startNew: '新規開始',
        delete: '削除',
    },
    test: {
        title: 'テスト',
        gpsSimulation: 'GPSシミュレーション',
        skiingSimul: '滑走シミュ',
        liftSimul: 'リフトシミュ',
        restingSimul: '休憩シミュ',
        fullDaySimul: '総合テスト (5ラン)',
        stopSimulation: 'シミュレーション停止',
        playbackSpeed: '再生速度:',
        unitTests: 'ユニットテスト',
        runningTests: 'テスト実行中...',
        simulationTest: 'シミュレーションテスト',
        syncTest: '同期テスト',
        simulationResults: 'シミュレーション結果',
        syncResults: '同期結果:',
        location: '位置:',
        altitude: '高度:',
        speed: '速度:',
        liveStats: 'リアルタイムスタッツ',
        expectedRuns: '予想ラン: 5回',
    },
}
