export const jp = {
    common: {
        welcome: 'ようこそ',
        hello: 'こんにちは',
        goodbye: 'さようなら',
        save: '保存',
        cancel: 'キャンセル',
        confirm: '確認',
        delete: '削除',
        edit: '編集',
        loading: '読み込み中...',
        error: 'エラー',
        success: '成功',
    },
    home: {
        title: 'ホーム',
        description: 'app/index.tsxを編集して始めましょう。',
        browseTheDocs: 'ドキュメントを見る',
        starTheRepo: 'リポジトリにスターをつける',
        about: '紹介',
    },
    navigator: {
        start: 'スタート',
    },
    history: {
        title: '履歴',
    },
    rank: {
        title: 'ランキング',
        selectCountry: '国を選択',
        selectResort: 'スキー場を選択',
        searchCountry: '国名を入力',
        searchResort: 'スキー場名を入力',
        speed: 'スピード',
        distance: '距離',
        count: '回数',
    },
    user: {
        title: 'プロフィール',
        editProfile: 'プロフィール編集',
        profileImage: 'プロフィール画像',
        name: '名前',
        bio: '自己紹介',
        isPublic: '公開設定',
        public: '公開',
        private: '非公開',
        save: '保存',
        cancel: 'キャンセル',
        tapToChange: 'タップして変更',
        totalSummary: '合計',
        activityType: 'アクティビティタイプ',
        ski: 'スキー',
        snowboard: 'スノーボード',
        both: 'スキー & スノーボード',
    },
    auth: {
        login: 'ログイン',
        logout: 'ログアウト',
        loginRequired: 'ログインが必要です',
        loginDescription: 'アカウントにログインしてアクティビティを記録しましょう',
        continueWithGoogle: 'Googleで続ける',
        continueWithApple: 'Appleで続ける',
        loginFailed: 'ログインに失敗しました',
        tryAgain: 'もう一度お試しください',
    },
    settings: {
        title: '設定',
        language: '言語',
        theme: 'テーマ',
        darkMode: 'ダークモード',
        lightMode: 'ライトモード',
        systemTheme: 'システム',
        units: '単位',
        temperature: '温度',
        measurement: '測定',
        celsius: '°C',
        fahrenheit: '°F',
        metric: 'メートル法',
        imperial: 'ヤードポンド法',
        notifications: '通知',
        feed: 'フィード',
        workout: 'ワークアウト',
        goal: '目標',
        on: 'オン',
        off: 'オフ',
    },
    uicard: {
        type: 'タイプ',
        totalDistance: '総距離',
        vertical: '垂直移動',
        maxSpeed: '最高速度',
        timeOnSlope: 'スロープ時間',
        runs: 'ラン',
    },
    tracking: {
        totalDistance: '距離',
        maxVertical: '垂直移動',
        totalRuns: 'ラン',
        maxSpeed: '最高速度',
        totalTime: '時間',
    },
}
