export const ko = {
    common: {
        welcome: '환영합니다',
        hello: '안녕하세요',
        goodbye: '안녕히 가세요',
        save: '저장',
        cancel: '취소',
        confirm: '확인',
        delete: '삭제',
        edit: '수정',
        loading: '로딩 중...',
        error: '오류',
        success: '성공',
    },
    home: {
        title: '홈',
        description: 'app/index.tsx 파일을 수정하여 시작하세요.',
        browseTheDocs: '문서 보기',
        starTheRepo: '저장소에 별 주기',
        about: '소개',
    },
    navigator: {
        start: '시작',
    },
    history: {
        title: '기록',
        follow: '팔로우',
        unfollow: '언팔로우',
        hide: '숨기기',
        report: '신고',
        friend: '친구',
        all: '전체',
        privateUser: '비공개 사용자',
        noItems: '활동 내역이 없습니다',
    },
    rank: {
        title: '랭킹',
        selectCountry: '나라 선택',
        selectResort: '스키장 선택',
        searchCountry: '나라 이름 입력',
        searchResort: '스키장 이름 입력',
        selectCountryFirst: '먼저 나라를 선택하세요',
        noRankings: '랭킹이 없습니다',
        speed: '스피드',
        distance: '거리',
        count: '횟수',
    },
    alarm: {
        title: '알림',
        unread: '읽지 않음',
        markAllAsRead: '모두 읽음 처리',
        noAlarms: '알림이 없습니다',
    },
    user: {
        title: '프로필',
        editProfile: '프로필 수정',
        profileImage: '프로필 이미지',
        name: '이름',
        bio: '내 소개',
        isPublic: '공개 여부',
        public: '공개',
        private: '비공개',
        save: '저장',
        cancel: '취소',
        tapToChange: '탭하여 변경',
        totalSummary: '총계',
        activityType: '활동 유형',
        ski: '스키',
        snowboard: '스노보드',
        both: '스키 & 스노보드',
    },
    auth: {
        login: '로그인',
        logout: '로그아웃',
        loginRequired: '로그인이 필요합니다',
        loginDescription: '계정에 로그인하여 활동을 기록하세요',
        continueWithGoogle: 'Google로 계속하기',
        continueWithApple: 'Apple로 계속하기',
        loginFailed: '로그인에 실패했습니다',
        tryAgain: '다시 시도해주세요',
    },
    settings: {
        title: '설정',
        language: '언어',
        theme: '테마',
        darkMode: '다크 모드',
        lightMode: '라이트 모드',
        systemTheme: '시스템',
        units: '단위',
        temperature: '온도',
        measurement: '측정',
        celsius: '°C',
        fahrenheit: '°F',
        metric: '미터법',
        imperial: '야드파운드법',
        notifications: '알림',
        feed: '피드',
        workout: '운동',
        goal: '목표',
        on: '켜짐',
        off: '꺼짐',
    },
    uicard: {
        type: '유형',
        totalDistance: '총 거리',
        vertical: '수직 이동',
        maxSpeed: '최고 속도',
        timeOnSlope: '슬로프 시간',
        runs: '런',
    },
    tracking: {
        totalDistance: '거리',
        maxVertical: '수직 이동',
        totalRuns: '런',
        maxSpeed: '최고 속도',
        totalTime: '시간',
    },
}
