export const ko = {
    common: {
        welcome: '환영합니다',
        hello: '안녕하세요',
        goodbye: '안녕히 가세요',
        save: '저장',
        cancel: '취소',
        confirm: '확인',
        delete: '삭제',
        edit: '수정',
        loading: '로딩 중...',
        error: '오류',
        success: '성공',
    },
    home: {
        title: '홈',
        description: 'app/index.tsx 파일을 수정하여 시작하세요.',
        browseTheDocs: '문서 보기',
        starTheRepo: '저장소에 별 주기',
        about: '소개',
    },
    navigator: {
        start: '시작',
    },
    history: {
        title: '기록',
        follow: '팔로우',
        unfollow: '언팔로우',
        hide: '숨기기',
        report: '신고',
        friend: '친구',
        all: '전체',
        privateUser: '비공개 사용자',
        noItems: '활동 내역이 없습니다',
        unknownResort: '알 수 없는 위치',
    },
    localHistory: {
        title: '내 기록',
        noItems: '로컬에 저장된 기록이 없습니다',
        noItemsDescription: '트래킹을 시작하면 여기에 기록이 표시됩니다',
        notSynced: '미동기화',
    },
    rank: {
        title: '랭킹',
        all: '전체',
        selectRegion: '지역 선택',
        selectResort: '스키장 선택',
        noRankings: '랭킹이 없습니다',
        speed: '속도',
        distance: '거리',
        count: '횟수',
    },
    alarm: {
        title: '알림',
        unread: '읽지 않음',
        markAllAsRead: '모두 읽음 처리',
        noAlarms: '알림이 없습니다',
    },
    user: {
        title: '프로필',
        editProfile: '프로필 수정',
        profileImage: '프로필 이미지',
        name: '이름',
        bio: '내 소개',
        isPublic: '공개 여부',
        public: '공개',
        private: '비공개',
        save: '저장',
        cancel: '취소',
        tapToChange: '탭하여 변경',
        totalSummary: '총계',
        activityType: '활동 유형',
        ski: '스키',
        snowboard: '스노보드',
        both: '스키 & 스노보드',
    },
    auth: {
        login: '로그인',
        logout: '로그아웃',
        loginRequired: '로그인이 필요합니다',
        loginDescription: '계정에 로그인하여 활동을 기록하세요',
        continueWithGoogle: 'Google로 계속하기',
        continueWithApple: 'Apple로 계속하기',
        loginFailed: '로그인에 실패했습니다',
        tryAgain: '다시 시도해주세요',
    },
    settings: {
        title: '설정',
        language: '언어',
        theme: '테마',
        darkMode: '다크 모드',
        lightMode: '라이트 모드',
        systemTheme: '시스템',
        units: '단위',
        temperature: '온도',
        measurement: '측정',
        celsius: '°C',
        fahrenheit: '°F',
        metric: '미터법',
        imperial: '야드파운드법',
        notifications: '알림',
        feed: '피드',
        workout: '운동',
        goal: '목표',
        on: '켜짐',
        off: '꺼짐',
        data: '데이터',
        resortData: '스키장 데이터',
        refreshResortData: '스키장 데이터 새로고침',
        resortDataUpdated: '스키장 데이터가 업데이트되었습니다',
        resortDataUpToDate: '최신 데이터입니다',
        resortDataError: '데이터 업데이트에 실패했습니다',
        version: '버전',
    },
    uicard: {
        type: '유형',
        totalDistance: '총 거리',
        vertical: '누적 고도',
        maxSpeed: '최고 속도',
        timeOnSlope: '활강 시간',
        runs: '활강 횟수',
    },
    tracking: {
        totalDistance: '거리',
        maxVertical: '최대 고도',
        totalRuns: '활강 횟수',
        maxSpeed: '최고 속도',
        totalTime: '시간',
        timeOnSlope: '활강 시간',
        skiing: '라이딩 중',
        lifting: '리프트 탑승',
        resting: '휴식 중',
        restingAlert: '30분 이상 움직임이 없습니다. 트래킹을 종료하시겠습니까?',
    },
    recovery: {
        title: '이전 기록이 있습니다',
        start: '시작',
        distance: '거리',
        runs: '활강',
        runUnit: '회',
        locationRecords: '위치 기록',
        countUnit: '개',
        resume: '이어서 기록',
        startNew: '새로 시작',
        delete: '삭제',
    },
    test: {
        title: '테스트',
        gpsSimulation: 'GPS 시뮬레이션',
        skiingSimul: '라이딩 시뮬',
        liftSimul: '리프트 시뮬',
        restingSimul: '휴식 시뮬',
        fullDaySimul: '종합 테스트 (5런)',
        stopSimulation: '시뮬레이션 중지',
        playbackSpeed: '재생 속도:',
        unitTests: '유닛 테스트',
        runningTests: '테스트 실행 중...',
        simulationTest: '시뮬레이션 테스트',
        syncTest: '동기화 테스트',
        simulationResults: '시뮬레이션 결과',
        syncResults: '동기화 결과:',
        location: '위치:',
        altitude: '고도:',
        speed: '속도:',
        liveStats: '실시간 스탯',
        expectedRuns: '예상 런: 5회',
    },
}
